import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
const inter = Inter({ subsets: ['latin'] });
import { useState } from 'react';

export default function Home() {
  const [user, setUser] = useState('');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1>{user && user.userName}</h1>
        <div className={styles.container}>
          Thank you for visiting our website (Redeem FC). Please note that the
          site is currently under construction and some pages may not be
          available at this time. We apologize for any inconvenience this may
          cause. We are working hard to complete the site and appreciate your
          patience. Please check back soon for updates and the official launch
          of our new and improved website. Thank you for your understanding.
        </div>
      </main>
    </>
  );
}
