import Head from 'next/head';
import { useSession, signOut } from 'next-auth/react';
const Home = () => {
    const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Redeem FC</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main>
        <header
          className=' container d-flex align-items-center justify-content-center hero-section hero-section-custom text-center text-light'
          style={{
            backgroundImage:
              "url('https://res.cloudinary.com/dzajrh9z7/image/upload/v1686571605/depositphotos_42274529-stock-photo-a-player-shooting-on-goal_mxhvjy.webp')",
          }}
        >
          <div className='container '>
            <h1>
              Welcome {session && session.user.name.split(' ')[1]} to Redeem
              Football Club
            </h1>
            <p className='lead'>
              Join us and be part of an amazing football journey
            </p>
            <a href='#' className='btn btn-primary'>
              Get Started
            </a>
          </div>
        </header>

        <section className='container  p-5  image-gallery mt-2 '>
          <div>
            <h2 className='text-center mb-3'>For the love of Football</h2>
            <div className='row mx-auto'>
              <div className='col-md-4 '>
                <img
                  src='https://res.cloudinary.com/dzajrh9z7/image/upload/v1686572664/images_6_ml6zsd.jpg'
                  className='img-fluid img-thumbnail'
                  alt='Image 1'
                />
              </div>
              <div className='col-md-4'>
                <img
                  src='https://res.cloudinary.com/dzajrh9z7/image/upload/v1686572664/images_8_a8cw2g.jpg'
                  className='img-fluid img-thumbnail'
                  alt='Image 3'
                />
              </div>
              <div className='col-md-4'>
                <img
                  src='https://res.cloudinary.com/dzajrh9z7/image/upload/v1686572664/images_7_rln3tp.jpg'
                  className='img-fluid img-thumbnail'
                  alt='Image 2'
                />
              </div>
            </div>
          </div>
        </section>

        <section className='about-section  mt-4'>
          <div className='container'>
            <h2 className='text-center'>About Redeem Football Club</h2>
            <p>
              Redeem FC is a premier football club committed to excellence and
              the pursuit of victory. With a rich history and a dedicated team
              of players, coaches, and staff, we strive to deliver exceptional
              performances on and off the field. Our club values teamwork,
              passion, and the relentless pursuit of success. Join us today and
              be part of our football family!
            </p>
          </div>
        </section>

        <section className='contact-section'>
          <div className='container'>
            <h2 className='text-center'>Contact Us</h2>
            <p>
              If you have any inquiries, suggestions, or feedback, feel free to
              get in touch with us. Our team is always ready to assist you and
              provide you with the information you need.
            </p>
            <p>Email: info@redeemfc.com</p>
            <p>Phone: +234 802 9707 512</p>
          </div>
        </section>

        <footer className='footer bg-dark text-white text-center py-3'>
          <p>&copy; 2023 Redeem Football Club. All rights reserved.</p>
        </footer>
      </main>

      <style jsx>{`
        /* Custom styles go here */

        .hero-section {
          background-size: cover;
          background-position: center;
          background-repeat: no-repeat;
          /* Add any additional styles for the hero section */
        }

        .hero-section-custom {
          height: 400px; /* Adjust the height as desired */
          background-color: #333; /* Add background color */
          background-blend-mode: overlay; /* Add texture overlay */
          background-image: url('path/to/texture-image.png'); /* Add texture image */
        }

        .image-gallery {
          /* Add styles for the image gallery section */
        }

        .about-section {
          /* Add styles for the about section */
        }

        .contact-section {
          /* Add styles for the contact section */
        }

        .footer {
          /* Add styles for the footer */
        }

        .img-thumbnail {
          border: 1px solid #ccc;
          box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
      `}</style>
    </>
  );
};

export default Home;
